---
title: "Plot EP DLPFC"
author: "Xianqing"
date: "3/31/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(readr)
library(patchwork)
library(ggsignif)
library(psych) # load correlation
library(RColorBrewer)#color
# setwd("C:/Users/xjl19/Desktop/TMS-iEEG/es-TT_Processed")
# load("C:/Users/xjl19/Desktop/TMS-iEEG/Stanford_Processed/TEP/CCEP_all.RData")

```


```{r}
# LDLPFC
normwave_hipp <- CCEP_hipp_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(13))
# normwave_hipp_pos <- filter(CCEP_hipp_avg, is_ant == 0) %>% group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt())
# normwave_hipp_ant <- filter(CCEP_hipp_avg, is_ant == 1) %>% group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt())
normwave_hipp_L <- filter(CCEP_hipp_avg, DKT == "Left-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(10))
normwave_hipp_R <- filter(CCEP_hipp_avg, DKT == "Right-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(3))

#LVLPFC
normwave_hipp <- CCEP_hipp_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(24))
normwave_hipp_L <- filter(CCEP_hipp_avg, DKT == "Left-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(12))
normwave_hipp_R <- filter(CCEP_hipp_avg, DKT == "Right-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(12))

# normwave_hipp_pos_L <- 
#   filter(CCEP_hipp_avg, is_ant == 0 & DKT == "Left-Hippocampus") %>% 
#   group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
# normwave_hipp_pos_R <- 
#   filter(CCEP_hipp_avg, is_ant == 0 & DKT == "Right-Hippocampus") %>% 
#   group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(10))
# normwave_hipp_ant_L <- 
#   filter(CCEP_hipp_avg, is_ant == 1 & DKT == "Left-Hippocampus") %>% 
#   group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(3))
# normwave_hipp_ant_R <- 
#   filter(CCEP_hipp_avg, is_ant == 1 & DKT == "Right-Hippocampus") %>% 
#   group_by(Time) %>%
#   summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(10))
```


```{r Both}
# normwave_hipp <- normwave_hipp %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
# normwave_hipp_pos <- normwave_hipp_pos %>% mutate(subdivision = "Posterior", iESsite = "L-DLPFC")
# normwave_hipp_ant <- normwave_hipp_ant %>% mutate(subdivision = "Anterior", iESsite = "L-DLPFC")
# normwave_bi <- rbind(normwave_amy, normwave_hipp_me, normwave_hipp_la)
# normwave_bi$subdivision <- 
#   factor(normwave_bi$subdivision, levels=c("Whole","Anterior","Posterior"))

p.norm_bi <- normwave_hipp %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "gray40", alpha = .2)+
  geom_line(col = "gray40",size=1.2)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral HIPP = 13")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_bi

# LVLPFC
p.norm_bi <- normwave_hipp %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "gray40", alpha = .2)+
  geom_line(col = "gray40",size=1.2)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral HIPP = 24")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_bi

# p.norm_mela_latency <- normwave_bi %>% ggplot(aes(Time, norm))+
#   geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
#   geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
#   geom_line(aes(col = subdivision),size=1.2)+
#   annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2.25, fill="gray")+
#   scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_y_continuous(limits=c(-13,15.4), breaks = c(-10,-5,0,5,10,15))+
#   scale_x_continuous(limits=c(-8,250), breaks = c(0,50,100,150,200,250))+
#   xlab("Time (ms)")+ylab("Amplitude (SD)")+theme_classic()+
#   theme(axis.line=element_line(linetype=1,color="black",size=.8))+
#   theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
#   theme(axis.text = element_text(color = "black", size = rel(1.5)))+
#   theme(axis.title = element_text(color = "black", size = 18))+
#   theme(plot.title = element_text(color = "black", size = 18))+
#   theme(legend.text = element_text(color = "black", size = rel(1.5)),
#         legend.position=c(0.18,0.2))+labs(fill="",col="")
# p.norm_mela_latency
```


```{r Left}
p.norm_L <- normwave_hipp_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "gray40", alpha = .2)+
  geom_line(col = "gray40",size=1.2)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral HIPP = 10")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_L


# normwave_hipp_L <- normwave_hipp_L %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
# normwave_hipp_pos_L <- normwave_hipp_pos_L %>% mutate(subdivision = "Posterior", iESsite = "L-DLPFC")
# normwave_hipp_ant_L <- normwave_hipp_ant_L %>% mutate(subdivision = "Anterior", iESsite = "L-DLPFC")
# normwave_L <- rbind(normwave_hipp_L, normwave_hipp_pos_L, normwave_hipp_ant_L)
# normwave_L$subdivision <- 
#   factor(normwave_L$subdivision, levels=c("Whole","Anterior","Posterior"))
# 
# p.norm_L <- normwave_L %>% ggplot(aes(Time, norm))+
#   geom_hline(yintercept=0, size = .4, col = "darkgray")+
#   geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
#   geom_line(aes(col = subdivision),size=1.2)+
#   annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=6, fill="gray")+
#   scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
#   scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
#   xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
#   ggtitle("Left AMY, medial = 6, lateral = 3")+theme_classic()+
#   theme(axis.line=element_line(linetype=1,color="black",size=.6))+
#   theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
#   theme(axis.text = element_text(color = "black", size = rel(1.5)))+
#   theme(axis.title = element_text(color = "black", size = 18))+
#   theme(plot.title = element_text(color = "black", size = 18))+
#   theme(legend.position="none")+labs(fill="",col="")
# p.norm_L
```

```{r Right}
p.norm_R <- normwave_hipp_R %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "gray40", alpha = .2)+
  geom_line(col = "gray40",size=1.2)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral HIPP = 3")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_R
# normwave_hipp_R <- normwave_hipp_R %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
# normwave_hipp_pos_R <- normwave_hipp_pos_R %>% mutate(subdivision = "Posterior", iESsite = "L-DLPFC")
# normwave_hipp_ant_R <- normwave_hipp_ant_R %>% mutate(subdivision = "Anterior", iESsite = "L-DLPFC")
# normwave_R <- rbind(normwave_hipp_R, normwave_hipp_pos_R, normwave_hipp_ant_R)
# normwave_R$subdivision <- 
#   factor(normwave_R$subdivision, levels=c("Whole","Anterior","Posterior"))
# 
# p.norm_R <- normwave_R %>% ggplot(aes(Time, norm))+
#   geom_hline(yintercept=0, size = .4, col = "darkgray")+
#   geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
#   geom_line(aes(col = subdivision),size=1.2)+
#   # lateral = 0
#   #medial
#   annotate("rect", xmin=82, xmax=164, ymin=13.9, ymax=14.6, fill="green4")+
#   annotate("rect", xmin=407, xmax=447, ymin=13.9, ymax=14.6, fill="green4")+
#   annotate("rect", xmin=496, xmax=500, ymin=13.9, ymax=14.6, fill="green4")+
#   # whole
#   annotate("rect", xmin=13, xmax=35, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
#   annotate("rect", xmin=88, xmax=229, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
#   annotate("rect", xmin=315, xmax=337, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
#   annotate("rect", xmin=381, xmax=500, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
#   
#   annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
#   scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
#   scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
#   xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
#   ggtitle("Right AMY, medial = 10, lateral = 10")+theme_classic()+
#   theme(axis.line=element_line(linetype=1,color="black",size=.6))+
#   theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
#   theme(axis.text = element_text(color = "black", size = rel(1.5)))+
#   theme(axis.title = element_text(color = "black", size = 18))+
#   theme(plot.title = element_text(color = "black", size = 18))+
#   theme(legend.position="none")+labs(fill="",col="")
# p.norm_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_L-DLPFC_HIPP_2hp_nodetrend.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_bi
p.norm_L
p.norm_R
dev.off()

filename <- "CCEP_L-VLPFC_HIPP_2hp_nodetrend.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_bi
dev.off()
```


## amygdala vs hippocampus

```{r}
load("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/site_specificity_amy/CCEP/iESsite_specificity.RData")
# load("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/site_specificity_amy/CCEP/iESsite_specificity_200.RData")

CCEP_hipp_LVLPFC <- CCEP_hipp_B %>% filter(iESsite == "Control_L-VLPFC")

normwave_hipp_LVLPFC <- CCEP_hipp_LVLPFC %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(17)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_pos <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6)) %>% 
  mutate(subdivision = "Posterior", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_ant <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(11)) %>% 
  mutate(subdivision = "Anterior", iESsite = "Control: L-VLPFC")

normwave_hipp_LVLPFC_L <- CCEP_hipp_LVLPFC %>% 
  filter(DKT == "Left-Hippocampus") %>% group_by(Time) %>% 
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(14)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_L_pos <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 0 & DKT == "Left-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(5)) %>% 
  mutate(subdivision = "Posterior", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_L_ant <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 1 & DKT == "Left-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(9)) %>% 
  mutate(subdivision = "Anterior", iESsite = "Control: L-VLPFC")

normwave_hipp_LVLPFC_R <- CCEP_hipp_LVLPFC %>% 
  filter(DKT == "Right-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(3)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_R_pos <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 0 & DKT == "Right-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) %>% 
  mutate(subdivision = "Posterior", iESsite = "Control: L-VLPFC")
normwave_hipp_LVLPFC_R_ant <- CCEP_hipp_LVLPFC %>% 
  filter(is_ant == 1 & DKT == "Right-Hippocampus") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) %>% 
  mutate(subdivision = "Anterior", iESsite = "Control: L-VLPFC")



```


```{r Both}
normwave_avh_B <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la)[c(1:4)] %>% mutate(ROI = "Amygdala")
normwave_hipp <- normwave_hipp %>% mutate(subdivision = "Whole", ROI = "Hippocampus") 
normwave_avh_B <- rbind(normwave_avh_B, normwave_hipp)
normwave_avh_B$subdivision <- paste(normwave_avh_B$subdivision, normwave_avh_B$ROI, sep = " ") 
normwave_avh_B$subdivision <- factor(normwave_avh_B$subdivision, levels=c("Whole Hippocampus","Lateral Amygdala","Medial Amygdala","Whole Amygdala"))
normwave_avh_B$ROI <- factor(normwave_avh_B$ROI, levels=c("Amygdala","Hippocampus"))


p.norm_avh_B <- normwave_avh_B %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = ROI))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, size=ROI))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,.15))+
  # FDR
  
  # Cluster
  annotate("rect", xmin=91, xmax=142, ymin=13.9, ymax=14.6, fill="green4")+
  annotate("rect", xmin=345, xmax=432, ymin=13.9, ymax=14.6, fill="green4")+
  
  annotate("rect", xmin=-8, xmax=9, ymin=-3, ymax=5, fill="gray")+
  scale_color_manual(values=c("gray30","maroon3","green4","dodgerblue3"))+
  scale_fill_manual(values=c("gray30","maroon3","green4","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral AMY = 11(5/6) vs HIPP = 13")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)),
  legend.position=c(0.5,0.3))+labs(fill="",col="",linetype ="")
p.norm_avh_B

```

```{r Left}
normwave_avh_L <- rbind(normwave_amy_L, normwave_amy_me_L, normwave_amy_la_L)[c(1:4)] %>% mutate(ROI = "Amygdala")
normwave_hipp_L <- normwave_hipp_L %>% mutate(subdivision = "Whole", ROI = "Hippocampus") 
normwave_avh_L <- rbind(normwave_avh_L, normwave_hipp_L)
normwave_avh_L$subdivision <- paste(normwave_avh_L$subdivision, normwave_avh_L$ROI, sep = " ") 
normwave_avh_L$subdivision <- factor(normwave_avh_L$subdivision, levels=c("Whole Hippocampus","Lateral Amygdala","Medial Amygdala","Whole Amygdala"))
normwave_avh_L$ROI <- factor(normwave_avh_L$ROI, levels=c("Amygdala","Hippocampus"))

p.norm_avh_L <- normwave_avh_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = ROI))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, size=ROI))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,.15))+
  # FDR
  # annotate("rect", xmin=375, xmax=381, ymin=13.9, ymax=14.6, fill="green4")+
  
  # Cluster
  
  annotate("rect", xmin=-8, xmax=9, ymin=-3, ymax=5, fill="gray")+
  scale_color_manual(values=c("gray30","maroon3","green4","dodgerblue3"))+
  scale_fill_manual(values=c("gray30","maroon3","green4","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY = 7(1/6) vs HIPP = 10")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)),
  legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")+
  theme(legend.position="none")
p.norm_avh_L
```

```{r Right}
normwave_avh_R <- rbind(normwave_amy_me_R)[c(1:4)] %>% mutate(ROI = "Amygdala")
normwave_hipp_R <- normwave_hipp_R %>% mutate(subdivision = "Whole", ROI = "Hippocampus") 
normwave_avh_R <- rbind(normwave_avh_R, normwave_hipp_R)
normwave_avh_R$subdivision <- paste(normwave_avh_R$subdivision, normwave_avh_R$ROI, sep = " ") 
normwave_avh_R$subdivision <- factor(normwave_avh_R$subdivision, levels=c("Whole Hippocampus","Medial Amygdala"))
normwave_avh_R$ROI <- factor(normwave_avh_R$ROI, levels=c("Amygdala","Hippocampus"))


p.norm_avh_R <- normwave_avh_R %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = ROI))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, size=ROI))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,.15))+
  # FDR
  # annotate("rect", xmin=87, xmax=147, ymin=13.9, ymax=14.6, fill="green4")+
  # annotate("rect", xmin=375, xmax=406, ymin=13.9, ymax=14.6, fill="green4")+
  # Cluster
  annotate("rect", xmin=83, xmax=156, ymin=13.9, ymax=14.6, fill="green4")+
  annotate("rect", xmin=344, xmax=430, ymin=13.9, ymax=14.6, fill="green4")+
  
  annotate("rect", xmin=-8, xmax=9, ymin=-3, ymax=5, fill="gray")+
  scale_color_manual(values=c("gray30","green4"))+
  scale_fill_manual(values=c("gray30","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Right AMY = 4(4) vs HIPP = 3")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)),
  legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")+
  theme(legend.position="none")
p.norm_avh_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_avh_Cluster.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_avh_B
p.norm_avh_L
p.norm_avh_R
dev.off()


```








