---
title: "Plot EP DLPFC"
author: "Xianqing"
date: "3/31/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(readr)
library(patchwork)
library(ggsignif)
library(psych) # load correlation
library(RColorBrewer)#color
# setwd("C:/Users/xjl19/Desktop/TMS-iEEG/es-TT_Processed")
# load("C:/Users/xjl19/Desktop/TMS-iEEG/Stanford_Processed/TEP/CCEP_all.RData")

```

```{r plot CCEP components}
p.components_amy <- normwave_amy %>% filter(Time >=-80 & Time <=500) %>% 
  ggplot(aes(Time, norm))+
  geom_line(col = "dodgerblue2", size = 1.5)+
  geom_vline(xintercept=0, linetype="dashed")+
  annotate("rect", xmin=50, xmax=180, ymin=5.2, ymax=5.8, fill="orange2")+
  annotate("rect", xmin=200, xmax=450, ymin=5.2, ymax=5.8, fill="royalblue3")+
  annotate("rect", xmin=-8, xmax=8, ymin=-1.5, ymax=1.5, fill="gray")+
  scale_size_manual(values=c(1.5,0.8))+
  scale_x_continuous(limits=c(-80,550), breaks = c(0,100,200,300,400,500))+
  scale_y_continuous(limits=c(-3,6), breaks = c(-2,0,2,4,6))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="",linetype ="")
p.components_amy

# Save pdf
filename <- "CCEP_L-DLPFC_AMY_components.pdf"
pdf(file = filename, height = 4, width = 6.5)
p.components_amy
dev.off()
```


```{r}
normwave_amy <- CCEP_amy_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(11))
normwave_amy_me <- filter(CCEP_amy_avg, is_lateral == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(5))
normwave_amy_la <- filter(CCEP_amy_avg, is_lateral == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
normwave_amy_L <- filter(CCEP_amy_avg, DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(7))
normwave_amy_R <- filter(CCEP_amy_avg, DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(4))

normwave_amy_me_L <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0)
normwave_amy_me_R <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(4))
normwave_amy_la_L <- 
  filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
```

```{r for new data}
normwave_amy <- CCEP_amy_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(14))
normwave_amy_me <- filter(CCEP_amy_avg, is_lateral == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
normwave_amy_la <- filter(CCEP_amy_avg, is_lateral == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(8))
normwave_amy_L <- filter(CCEP_amy_avg, DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(9))
normwave_amy_R <- filter(CCEP_amy_avg, DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(5))

normwave_amy_me_L <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) # n = 2
normwave_amy_me_R <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(4))
normwave_amy_la_L <- 
  filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(7))
normwave_amy_la_R <- 
  filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Right-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) # n = 1
```

```{r for multi-sessions}
normwave_amy <- CCEP_amy_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(18))
normwave_amy_me <- filter(CCEP_amy_avg, is_lateral == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
normwave_amy_la <- filter(CCEP_amy_avg, is_lateral == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(12))
normwave_amy_L <- filter(CCEP_amy_avg, DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(13))
normwave_amy_R <- filter(CCEP_amy_avg, DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(5))

normwave_amy_me_L <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) # n = 2
normwave_amy_me_R <- 
  filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(4))
normwave_amy_la_L <- 
  filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(11))
normwave_amy_la_R <- 
  filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Right-Amygdala") %>% 
  group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) # n = 1
```


```{r Both}
normwave_amy <- normwave_amy %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me <- normwave_amy_me %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la <- normwave_amy_la %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_bi <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la)
normwave_bi$subdivision <- 
  factor(normwave_bi$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_bi <- normwave_bi %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  # lateral = 0
  # annotate("rect", xmin=115, xmax=168, ymin=13.2, ymax=13.8, fill="maroon3")+
  #medial
  annotate("rect", xmin=82, xmax=139, ymin=13.9, ymax=14.6, fill="green4")+
  annotate("rect", xmin=341, xmax=418, ymin=13.9, ymax=14.6, fill="green4")+
  # whole
  annotate("rect", xmin=119, xmax=166, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  annotate("rect", xmin=349, xmax=431, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  
  
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral AMY, medial = 5, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_bi

# p.norm_mela_latency <- normwave_bi %>% ggplot(aes(Time, norm))+
#   geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
#   geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
#   geom_line(aes(col = subdivision),size=1.2)+
#   annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2.25, fill="gray")+
#   scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
#   scale_y_continuous(limits=c(-13,15.4), breaks = c(-10,-5,0,5,10,15))+
#   scale_x_continuous(limits=c(-8,250), breaks = c(0,50,100,150,200,250))+
#   xlab("Time (ms)")+ylab("Amplitude (SD)")+theme_classic()+
#   theme(axis.line=element_line(linetype=1,color="black",size=.8))+
#   theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
#   theme(axis.text = element_text(color = "black", size = rel(1.5)))+
#   theme(axis.title = element_text(color = "black", size = 18))+
#   theme(plot.title = element_text(color = "black", size = 18))+
#   theme(legend.text = element_text(color = "black", size = rel(1.5)),
#         legend.position=c(0.18,0.2))+labs(fill="",col="")
# p.norm_mela_latency
```


```{r Left}
normwave_amy_L <- normwave_amy_L %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_L <- normwave_amy_me_L %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la_L <- normwave_amy_la_L %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_L <- rbind(normwave_amy_L, normwave_amy_me_L, normwave_amy_la_L)
normwave_L$subdivision <- 
  factor(normwave_L$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_L <- normwave_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  # whole = 0
  # annotate("rect", xmin=114, xmax=171, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  # medial = 0
  # lateral
  # annotate("rect", xmin=115, xmax=168, ymin=13.2, ymax=13.8, fill="maroon3")+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY, medial = 1, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_L
```

```{r Right}
normwave_amy_R <- normwave_amy_R %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_R <- normwave_amy_me_R %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_R <- rbind(normwave_amy_R, normwave_amy_me_R)
normwave_R$subdivision <- 
  factor(normwave_R$subdivision, levels=c("Whole","Medial"))

p.norm_R <- normwave_amy_me_R %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("green4"))+
  scale_fill_manual(values=c("green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Right AMY, medial = 4")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_L-DLPFC_AMY_2hp_nodetrend.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_bi
p.norm_L
p.norm_R
dev.off()
```


## L-DLPFC vs L-VLPFC

```{r}
load("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/site_specificity_amy/CCEP/iESsite_specificity.RData")
# load("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/site_specificity_amy/CCEP/iESsite_specificity_200.RData")

CCEP_amy_LVLPFC <- CCEP_amy_B %>% filter(iESsite == "Control_L-VLPFC")

normwave_amy_LVLPFC <- CCEP_amy_LVLPFC %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(17)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_me <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6)) %>% 
  mutate(subdivision = "Medial", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_la <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(11)) %>% 
  mutate(subdivision = "Lateral", iESsite = "Control: L-VLPFC")

normwave_amy_LVLPFC_L <- CCEP_amy_LVLPFC %>% 
  filter(DKT == "Left-Amygdala") %>% group_by(Time) %>% 
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(14)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_L_me <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 0 & DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(5)) %>% 
  mutate(subdivision = "Medial", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_L_la <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 1 & DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(9)) %>% 
  mutate(subdivision = "Lateral", iESsite = "Control: L-VLPFC")

normwave_amy_LVLPFC_R <- CCEP_amy_LVLPFC %>% 
  filter(DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(3)) %>% 
  mutate(subdivision = "Whole", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_R_me <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 0 & DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) %>% 
  mutate(subdivision = "Medial", iESsite = "Control: L-VLPFC")
normwave_amy_LVLPFC_R_la <- CCEP_amy_LVLPFC %>% 
  filter(is_lateral == 1 & DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = 0) %>% 
  mutate(subdivision = "Lateral", iESsite = "Control: L-VLPFC")



```


```{r Both}
normwave_amy_lvcl_B <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la, 
                             normwave_amy_LVLPFC, normwave_amy_LVLPFC_me, normwave_amy_LVLPFC_la)

normwave_amy_lvcl_B$subdivision <- paste(normwave_amy_lvcl_B$subdivision, normwave_amy_lvcl_B$iESsite, sep = " ") 
normwave_amy_lvcl_B$subdivision <- factor(normwave_amy_lvcl_B$subdivision, levels=c("Lateral L-DLPFC","Lateral Control: L-VLPFC","Medial L-DLPFC","Medial Control: L-VLPFC","Whole L-DLPFC","Whole Control: L-VLPFC"))
normwave_amy_lvcl_B$iESsite <- factor(normwave_amy_lvcl_B$iESsite, levels=c("L-DLPFC","Control: L-VLPFC"))


p.norm_lvcl_B <- normwave_amy_lvcl_B %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = iESsite))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, linetype = iESsite, size=iESsite))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,0))+
  # FDR
  # annotate("rect", xmin=83, xmax=138, ymin=14, ymax=14.6, fill="green4")+
  # annotate("rect", xmin=349, xmax=422, ymin=14, ymax=14.6, fill="green4")+
  # cluster
  annotate("rect", xmin=84, xmax=143, ymin=14, ymax=14.6, fill="green4")+
  annotate("rect", xmin=344, xmax=421, ymin=14, ymax=14.6, fill="green4")+
  
  annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2.25, fill="gray")+
  scale_color_manual(values=c("maroon3","maroon3","green4","green4",
                              "dodgerblue3","dodgerblue3"))+
  scale_fill_manual(values=c("maroon3","maroon3","green4","green4",
                              "dodgerblue3","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral AMY, medial = 5, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  # theme(legend.text = element_text(color = "black", size = rel(1.5)),
        # legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")
  theme(legend.position="none")
p.norm_lvcl_B

#### b200 ####
# p.norm_lvcl_B <- normwave_amy_lvcl_B %>% ggplot(aes(Time, norm))+
#   geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
#   geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .17)+
#   # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
#   geom_line(aes(col = subdivision, linetype = iESsite, size=iESsite))+
#   scale_size_manual(values=c(1.2,0.8))+
#   # whole 
#   annotate("rect", xmin=111, xmax=166, ymin=6.1, ymax=6.4, fill="dodgerblue3")+
#   annotate("rect", xmin=341, xmax=385, ymin=6.1, ymax=6.4, fill="dodgerblue3")+
#   # medial
#   annotate("rect", xmin=108, xmax=169, ymin=5.7, ymax=6, fill="green4")+
#   annotate("rect", xmin=378, xmax=412, ymin=5.7, ymax=6, fill="green4")+
# 
#   annotate("rect", xmin=-8, xmax=9, ymin=-1.5, ymax=1.5, fill="gray")+
#   scale_color_manual(values=c("maroon3","maroon3","green4","green4",
#                               "dodgerblue3","dodgerblue3"))+
#   scale_fill_manual(values=c("maroon3","maroon3","green4","green4",
#                               "dodgerblue3","dodgerblue3"))+
#   scale_y_continuous(limits=c(-5.8,6.4), breaks = c(-5,-2.5,0,2.5,5))+
#   scale_x_continuous(limits=c(-200,500), breaks = c(-200,-100,0,100,200,300,400,500))+
#   xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
#   ggtitle("Bilateral AMY, medial = 18, lateral = 12 (L-DLPFC site)")+theme_classic()+
#   theme(axis.line=element_line(linetype=1,color="black",size=.8))+
#   theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
#   theme(axis.text = element_text(color = "black", size = rel(1.5)))+
#   theme(axis.title = element_text(color = "black", size = 18))+
#   theme(plot.title = element_text(color = "black", size = 18))+
#   # theme(legend.text = element_text(color = "black", size = rel(1.5)),
#         # legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")
#   theme(legend.position="none")
# p.norm_lvcl_B

```

```{r Left}
normwave_amy_lvcl_L <- rbind(normwave_amy_L, normwave_amy_me_L, normwave_amy_la_L, 
                             normwave_amy_LVLPFC_L, normwave_amy_LVLPFC_L_me, normwave_amy_LVLPFC_L_la)

normwave_amy_lvcl_L$subdivision <- paste(normwave_amy_lvcl_L$subdivision, normwave_amy_lvcl_L$iESsite, sep = " ") 
normwave_amy_lvcl_L$subdivision <- factor(normwave_amy_lvcl_L$subdivision, levels=c("Lateral L-DLPFC","Lateral Control: L-VLPFC","Medial L-DLPFC","Medial Control: L-VLPFC","Whole L-DLPFC","Whole Control: L-VLPFC"))
normwave_amy_lvcl_L$iESsite <- factor(normwave_amy_lvcl_L$iESsite, levels=c("L-DLPFC","Control: L-VLPFC"))


p.norm_lvcl_L <- normwave_amy_lvcl_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = iESsite))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, linetype = iESsite, size=iESsite))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,0))+
  # FDR
  # annotate("rect", xmin=370, xmax=394, ymin=14, ymax=14.6, fill="green4")+
  # Cluster
  annotate("rect", xmin=363, xmax=409, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  
  annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2.25, fill="gray")+
  scale_color_manual(values=c("maroon3","maroon3","green4","green4",
                              "dodgerblue3","dodgerblue3"))+
  scale_fill_manual(values=c("maroon3","maroon3","green4","green4",
                              "dodgerblue3","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY, medial = 1, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  # theme(legend.text = element_text(color = "black", size = rel(1.5)),
        # legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")
  theme(legend.position="none")
p.norm_lvcl_L
```

```{r Right}
normwave_amy_lvcl_R <- rbind(normwave_amy_me_R, 
                             normwave_amy_LVLPFC_R, normwave_amy_LVLPFC_R_me, normwave_amy_LVLPFC_R_la)

normwave_amy_lvcl_R$subdivision <- paste(normwave_amy_lvcl_R$subdivision, normwave_amy_lvcl_R$iESsite, sep = " ") 
normwave_amy_lvcl_R$subdivision <- factor(normwave_amy_lvcl_R$subdivision, levels=c("Lateral Control: L-VLPFC","Medial L-DLPFC","Medial Control: L-VLPFC","Whole Control: L-VLPFC"))
normwave_amy_lvcl_R$iESsite <- factor(normwave_amy_lvcl_R$iESsite, levels=c("L-DLPFC","Control: L-VLPFC"))
summary(normwave_amy_lvcl_R)

p.norm_lvcl_R <- normwave_amy_lvcl_R %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0,  size = .8, col = "gray", alpha = .5)+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision, alpha = iESsite))+
  # geom_line(aes(col = subdivision, linetype = Condition),size=1.2)+
  geom_line(aes(col = subdivision, linetype = iESsite, size=iESsite))+
  scale_size_manual(values=c(1,0.7))+
  scale_alpha_manual(values=c(.17,0))+
  # FDR
  # annotate("rect", xmin=85, xmax=164, ymin=14, ymax=14.6, fill="green4")+
  # annotate("rect", xmin=337, xmax=425, ymin=14, ymax=14.6, fill="green4")+
  # annotate("rect", xmin=87, xmax=155, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  # annotate("rect", xmin=337, xmax=424, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  # cluster
  annotate("rect", xmin=86, xmax=163, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  annotate("rect", xmin=333, xmax=426, ymin=14.8, ymax=15.5, fill="dodgerblue3")+
  annotate("rect", xmin=9, xmax=32, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  annotate("rect", xmin=82, xmax=170, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  annotate("rect", xmin=226, xmax=259, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  annotate("rect", xmin=295, xmax=308, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  annotate("rect", xmin=331, xmax=435, ymin=14, ymax=14.6, fill="green4", alpha = 0.6)+
  annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2.25, fill="gray")+
  scale_color_manual(values=c("maroon3","green4","green4","dodgerblue3"))+
  scale_fill_manual(values=c("maroon3","green4","green4","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Right AMY, medial = 4")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  # theme(legend.text = element_text(color = "black", size = rel(1.5)),
        # legend.position=c(0.2,0.3))+labs(fill="",col="",linetype ="")
  theme(legend.position="none")
p.norm_lvcl_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_lvcl_AMY_Cluster.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_lvcl_B
p.norm_lvcl_L
p.norm_lvcl_R
dev.off()

filename <- "CCEP_lvcl_AMY_mela_corrected_b200.pdf"
pdf(file = filename, height = 5.5, width = 7.5)
p.norm_lvcl_B
dev.off()

filename <- "CCEP_lvcl_AMY_mela_latency.pdf"
pdf(file = filename, height = 5.5, width = 5)
p.norm_mela_latency
dev.off()

```

# sessions

```{r Both sessions}
normwave_amy <- normwave_amy %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me <- normwave_amy_me %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la <- normwave_amy_la %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_bi <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la)
normwave_bi$subdivision <- 
  factor(normwave_bi$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_bi <- normwave_bi %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  # lateral = 0
  # annotate("rect", xmin=115, xmax=168, ymin=13.2, ymax=13.8, fill="maroon3")+
  #medial
  annotate("rect", xmin=101, xmax=164, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=223, xmax=268, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=337, xmax=405, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  # whole
  annotate("rect", xmin=46, xmax=51, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=99, xmax=175, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=366, xmax=434, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=35, xmax=56, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=414, xmax=430, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  
  
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral AMY, medial = 5, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_bi
```

```{r Left sessions}
normwave_amy_L <- normwave_amy_L %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_L <- normwave_amy_me_L %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la_L <- normwave_amy_la_L %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_L <- rbind(normwave_amy_L, normwave_amy_me_L, normwave_amy_la_L)
normwave_L$subdivision <- 
  factor(normwave_L$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_L <- normwave_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
 
  # whole
  annotate("rect", xmin=29, xmax=87, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=149, xmax=170, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=298, xmax=322, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=35, xmax=57, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=414, xmax=428, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
 
  
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY, medial = 1, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_L
```

```{r Right sessions}
normwave_amy_R <- normwave_amy_R %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_R <- normwave_amy_me_R %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la_R <- normwave_amy_la_R %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_R <- rbind(normwave_amy_R, normwave_amy_me_R, normwave_amy_la_R)
normwave_R$subdivision <- 
  factor(normwave_R$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_R <- normwave_R %>% ggplot(aes(Time, norm))+
  
  
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  #medial
  annotate("rect", xmin=25, xmax=32, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=76, xmax=160, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=338, xmax=432, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  
  # whole
  annotate("rect", xmin=80, xmax=155, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=337, xmax=434, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY, medial = 1, lateral = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_L-DLPFC_AMY_sessions.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_bi
p.norm_L
p.norm_R
dev.off()
```

# New data 1/18/2024

```{r Both new}
normwave_amy <- normwave_amy %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me <- normwave_amy_me %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la <- normwave_amy_la %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_bi <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la)
normwave_bi$subdivision <- 
  factor(normwave_bi$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_bi <- normwave_bi %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  # lateral = 0
  # annotate("rect", xmin=115, xmax=168, ymin=13.2, ymax=13.8, fill="maroon3")+
  #medial
  annotate("rect", xmin=101, xmax=164, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=223, xmax=268, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=337, xmax=405, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  # whole
  annotate("rect", xmin=99, xmax=178, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=366, xmax=401, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=414, xmax=428, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=416, xmax=423, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  
  
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-15,-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral AMY, medial = 6, lateral = 8")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_bi
```

```{r Left new}
normwave_amy_L <- normwave_amy_L %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_L <- normwave_amy_me_L %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la_L <- normwave_amy_la_L %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_L <- rbind(normwave_amy_L, normwave_amy_me_L, normwave_amy_la_L)
normwave_L$subdivision <- 
  factor(normwave_L$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_L <- normwave_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
 
  # whole
  annotate("rect", xmin=33, xmax=61, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=72, xmax=83, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=294, xmax=324, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=46, xmax=50, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=314, xmax=322, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=416, xmax=423, ymin=13.0, ymax=13.7, fill="maroon3", alpha=.6)+
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
 
  
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left AMY, medial = 2, lateral = 7")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_L
```

```{r Right new}
normwave_amy_R <- normwave_amy_R %>% mutate(subdivision = "Whole", iESsite = "L-DLPFC")
normwave_amy_me_R <- normwave_amy_me_R %>% mutate(subdivision = "Medial", iESsite = "L-DLPFC")
normwave_amy_la_R <- normwave_amy_la_R %>% mutate(subdivision = "Lateral", iESsite = "L-DLPFC")
normwave_R <- rbind(normwave_amy_R, normwave_amy_me_R, normwave_amy_la_R)
normwave_R$subdivision <- 
  factor(normwave_R$subdivision, levels=c("Whole","Lateral","Medial"))

p.norm_R <- normwave_R %>% ggplot(aes(Time, norm))+
  
  
  geom_hline(yintercept=0, size = .4, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  #medial
  annotate("rect", xmin=25, xmax=32, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=76, xmax=160, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=338, xmax=432, ymin=13.9, ymax=14.6, fill="green4", alpha=.6)+
  annotate("rect", xmin=83, xmax=150, ymin=13.9, ymax=14.6, fill="green4")+
  annotate("rect", xmin=344, xmax=418, ymin=13.9, ymax=14.6, fill="green4")+
  
  # whole
  annotate("rect", xmin=80, xmax=155, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  annotate("rect", xmin=337, xmax=434, ymin=14.8, ymax=15.5, fill="dodgerblue3", alpha=.6)+
  
  annotate("rect", xmin=-8, xmax=8, ymin=-5, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_fill_manual(values=c("dodgerblue3","maroon3","green4"))+
  scale_y_continuous(limits=c(-13,15.5), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-100,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Right AMY, medial = 5, lateral = 1")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.6))+
  theme(axis.ticks=element_line(color="black",size=.6,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_R
```


```{r}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "CCEP_L-DLPFC_AMY_new.pdf"
pdf(file = filename, height = 4.6, width = 5.5)
p.norm_bi
p.norm_L
p.norm_R
dev.off()
```


