---
title: "Plot CCEP R-VLPFC"
author: "Xianqing"
date: "7/25/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(readr)
library(patchwork)
library(ggsignif)
library(psych) # load correlation
library(RColorBrewer)#color
setwd("C:/Users/xjl19/Desktop/TMS-iEEG/es-TT_Processed")
# load("C:/Users/xjl19/Desktop/TMS-iEEG/Stanford_Processed/TEP/iTEP_all.RData")
figDir = "/Users/xianqing/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
figDir = "C:/Users/xjl19/OneDrive - University of Iowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
```

```{r waveform whole AMY SDchange and EP}
SDwave_amy <- CCEP_amy_avg %>% group_by(Time) %>%
  summarise(SD = mean(SDchange), se = sd(SDchange)/sqrt(29)) 
p.SD_amy <- SDwave_amy %>% ggplot(aes(Time, SD))+
  geom_ribbon(aes(ymin=SD-se, ymax=SD+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # 35
  annotate("rect", xmin=10, xmax=74, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=90, xmax=242, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=254, xmax=450, ymin=7.75, ymax=8, fill="dodgerblue3")+

  annotate("rect", xmin=-8, xmax=9, ymin=0, ymax=4.2, fill="gray")+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylim(-1,8)+
  ylab("Absolute amplitude (SD)")+ ggtitle("AMY  n = 29")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.SD_amy

normwave_amy <- CCEP_amy_avg %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(29))
p.norm_amy <- normwave_amy %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # 35
  annotate("rect", xmin=44, xmax=56, ymin=14, ymax=14.7, fill="dodgerblue3")+
  annotate("rect", xmin=149, xmax=182, ymin=14, ymax=14.7, fill="dodgerblue3")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-1.5, ymax=4, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY  n = 29")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy

# Save pdf
filename <- "CCEP_R-DLPFC_AMY_bi_35Hz.pdf"
pdf(file = filename, height = 5, width = 9)
p.norm_amy
dev.off()

filename <- "CCEP_R-DLPFC_AMY_sub_35Hz.pdf"
pdf(file = filename, height = 4.5, width = 5)
p.norm_amy_L
p.norm_amy_R
p.norm_amy_me
p.norm_amy_la
p.norm_amy_me_L 
p.norm_amy_me_R 
p.norm_amy_la_L 
p.norm_amy_la_R 
dev.off()

filename <- "CCEP_AMY_R-DLPFC.pdf"
filename <- "CCEP_AMY_R-DLPFC_removed_cleaned.pdf"
pdf(file = filename, height = 5, width = 8)
p.SD_amy
p.norm_amy
p.SD_amy_L
p.norm_amy_L
p.SD_amy_R
p.norm_amy_R
p.SD_amy_me
p.norm_amy_me
p.SD_amy_la
p.norm_amy_la
dev.off()
```

```{r waveform left AMY SDchange and EP}
SDwave_amy_L <- filter(CCEP_amy_avg, DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(SD = mean(SDchange), se = sd(SDchange)/sqrt(9)) 
p.SD_amy_L <- SDwave_amy_L %>% ggplot(aes(Time, SD))+
  geom_ribbon(aes(ymin=SD-se, ymax=SD+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # all
  # annotate("rect", xmin=103, xmax=114, ymin=7.75, ymax=8, fill="dodgerblue3")+
  
  # cleaned
  annotate("rect", xmin=90, xmax=129, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=-8, xmax=9, ymin=0, ymax=3.5, fill="gray")+
  ylim(-1,8)+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Absolute amplitude (SD)")+ ggtitle("AMY Left  n = 9")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.SD_amy_L

normwave_amy_L <- filter(CCEP_amy_avg, DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(9))
p.norm_amy_L <- normwave_amy_L %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # 35
  annotate("rect", xmin=90, xmax=122, ymin=14, ymax=14.7, fill="dodgerblue3")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=3, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Left  n = 9")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_L

```


```{r waveform Right AMY SDchange and EP}
SDwave_amy_R <- filter(CCEP_amy_avg, DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(SD = mean(SDchange), se = sd(SDchange)/sqrt(20)) 
p.SD_amy_R <- SDwave_amy_R %>% ggplot(aes(Time, SD))+
  geom_ribbon(aes(ymin=SD-se, ymax=SD+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # all
  # annotate("rect", xmin=10, xmax=71, ymin=7.75, ymax=8, fill="dodgerblue3")+
  # annotate("rect", xmin=96, xmax=247, ymin=7.75, ymax=8, fill="dodgerblue3")+
  # annotate("rect", xmin=254, xmax=450, ymin=7.75, ymax=8, fill="dodgerblue3")+
  
  # cleaned
  annotate("rect", xmin=10, xmax=72, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=101, xmax=242, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=258, xmax=450, ymin=7.75, ymax=8, fill="dodgerblue3")+
  annotate("rect", xmin=-8, xmax=9, ymin=0, ymax=5.2, fill="gray")+
  ylim(-1,8)+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Absolute amplitude (SD)")+ ggtitle("AMY Right  n = 20")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.SD_amy_R

normwave_amy_R <- filter(CCEP_amy_avg, DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(20))
p.norm_amy_R <- normwave_amy_R %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "dodgerblue3", alpha = .25)+
  geom_line(col = "dodgerblue3",size=1.2)+
  # 35
  annotate("rect", xmin=146, xmax=210, ymin=14, ymax=14.7, fill="dodgerblue3")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=2, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Right  n = 20")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_R
```


```{r waveform Medial AMY SDchange and EP}
SDwave_amy_me <- filter(CCEP_amy_avg, is_lateral == 0) %>% group_by(Time) %>%
  summarise(SD = mean(SDchange), se = sd(SDchange)/sqrt(16)) 
p.SD_amy_me <- SDwave_amy_me %>% ggplot(aes(Time, SD))+
  geom_ribbon(aes(ymin=SD-se, ymax=SD+se), fill = "green4", alpha = .25)+
  geom_line(col = "green4",size=1.2)+
  # all
  # annotate("rect", xmin=10, xmax=23, ymin=7.75, ymax=8, fill="green4")+
  # annotate("rect", xmin=93, xmax=162, ymin=7.75, ymax=8, fill="green4")+
  # annotate("rect", xmin=411, xmax=423, ymin=7.75, ymax=8, fill="green4")+
  
  # cleaned
  annotate("rect", xmin=38, xmax=75, ymin=7.75, ymax=8, fill="green4")+
  annotate("rect", xmin=88, xmax=198, ymin=7.75, ymax=8, fill="green4")+
  annotate("rect", xmin=258, xmax=286, ymin=7.75, ymax=8, fill="green4")+
  annotate("rect", xmin=377, xmax=425, ymin=7.75, ymax=8, fill="green4")+
  annotate("rect", xmin=-8, xmax=9, ymin=0, ymax=4.5, fill="gray")+
  ylim(-1,8)+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Absolute amplitude (SD)")+ ggtitle("AMY Medial  n = 16")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.SD_amy_me

normwave_amy_me <- filter(CCEP_amy_avg, is_lateral == 0) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(16))
p.norm_amy_me <- normwave_amy_me %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "green4", alpha = .25)+
  geom_line(col = "green4",size=1.2)+
  # 35
  annotate("rect", xmin=86, xmax=131, ymin=14, ymax=14.7, fill="green4")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=3.8, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Medial  n = 16")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_me

```


```{r waveform Lateral AMY SDchange and EP}
SDwave_amy_la <- filter(CCEP_amy_avg, is_lateral == 1) %>% group_by(Time) %>%
  summarise(SD = mean(SDchange), se = sd(SDchange)/sqrt(13)) 
p.SD_amy_la <- SDwave_amy_la %>% ggplot(aes(Time, SD))+
  geom_ribbon(aes(ymin=SD-se, ymax=SD+se), fill = "maroon3", alpha = .25)+
  geom_line(col = "maroon3",size=1.2)+
  # all 
  # annotate("rect", xmin=10, xmax=70, ymin=7.75, ymax=8, fill="maroon3")+
  # annotate("rect", xmin=102, xmax=234, ymin=7.75, ymax=8, fill="maroon3")+
  # annotate("rect", xmin=259, xmax=450, ymin=7.75, ymax=8, fill="maroon3")+
  # cleaned
  annotate("rect", xmin=10, xmax=30, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=35, xmax=65, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=111, xmax=151, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=157, xmax=214, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=264, xmax=385, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=411, xmax=450, ymin=7.75, ymax=8, fill="maroon3")+
  annotate("rect", xmin=-8, xmax=9, ymin=0, ymax=5, fill="gray")+
  ylim(-1,8)+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Absolute amplitude (SD)")+ ggtitle("AMY Lateral  n = 13")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.SD_amy_la

normwave_amy_la <- filter(CCEP_amy_avg, is_lateral == 1) %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(13))
p.norm_amy_la <- normwave_amy_la %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "maroon3", alpha = .25)+
  geom_line(col = "maroon3",size=1.2)+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  # 35
  annotate("rect", xmin=40, xmax=62, ymin=14, ymax=14.7, fill="maroon3")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2.2, ymax=2, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Lateral  n = 13")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_la

```


```{r waveform Medial AMY left and right}
normwave_amy_me_L <- filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(6))
p.norm_amy_me_L <- normwave_amy_me_L %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "green4", alpha = .25)+
  geom_line(col = "green4",size=1.2)+
  # 35
  annotate("rect", xmin=92, xmax=123, ymin=14, ymax=14.7, fill="green4")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=3.8, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Left medial  n = 6")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_me_L

normwave_amy_me_R <- filter(CCEP_amy_avg, is_lateral == 0 & DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(10))
p.norm_amy_me_R <- normwave_amy_me_R %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "green4", alpha = .25)+
  geom_line(col = "green4",size=1.2)+
  # 35
  annotate("rect", xmin=89, xmax=115, ymin=14, ymax=14.7, fill="green4")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=3.8, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Right medial  n = 10")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_me_R

```


```{r waveform Lateral AMY left and right}
normwave_amy_la_L <- filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Left-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(3))
p.norm_amy_la_L <- normwave_amy_la_L %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "maroon3", alpha = .25)+
  geom_line(col = "maroon3",size=1.2)+

  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2, ymax=5, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Left lateral  n = 3")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_la_L

normwave_amy_la_R <- filter(CCEP_amy_avg, is_lateral == 1 & DKT == "Right-Amygdala") %>% group_by(Time) %>%
  summarise(norm = mean(CCEP_norm), se = sd(CCEP_norm)/sqrt(10))
p.norm_amy_la_R <- normwave_amy_la_R %>% ggplot(aes(Time, norm))+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se), fill = "maroon3", alpha = .25)+
  geom_line(col = "maroon3",size=1.2)+
  # 35
  annotate("rect", xmin=43, xmax=60, ymin=14, ymax=14.7, fill="maroon3")+
  annotate("rect", xmin=163, xmax=182, ymin=14, ymax=14.7, fill="maroon3")+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  annotate("rect", xmin=-8, xmax=9, ymin=-2.5, ymax=2, fill="gray")+
  scale_y_continuous(limits=c(-13,15), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-150,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+
  ylab("Amplitude (SD)")+ ggtitle("AMY Right lateral  n = 10")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)))
p.norm_amy_la_R

```



```{r p.norm_bi}
normwave_amy <- normwave_amy %>% mutate(subdivision = "Whole")
normwave_amy_me <- normwave_amy_me %>% mutate(subdivision = "Medial")
normwave_amy_la <- normwave_amy_la %>% mutate(subdivision = "Lateral")
normwave_bi <- rbind(normwave_amy, normwave_amy_me, normwave_amy_la)
normwave_bi$subdivision <- 
  factor(normwave_bi$subdivision, levels=c("Lateral","Medial","Whole"))

p.norm_bi <- normwave_bi %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  # whole
  annotate("rect", xmin=54, xmax=66, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  annotate("rect", xmin=169, xmax=218, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  annotate("rect", xmin=383, xmax=436, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  # medial
  annotate("rect", xmin=413, xmax=425, ymin=14, ymax=14.6, fill="green4")+
  # lateral 
  annotate("rect", xmin=173, xmax=190, ymin=13.2, ymax=13.8, fill="maroon3")+
  annotate("rect", xmin=378, xmax=400, ymin=13.2, ymax=13.8, fill="maroon3")+
  
  annotate("rect", xmin=-8, xmax=10, ymin=-2.2, ymax=2.25, fill="gray")+
  scale_color_manual(values=c("maroon3","green4","dodgerblue3"))+
  scale_fill_manual(values=c("maroon3","green4","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.4), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-120,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Bilateral (26), medial = 14, lateral = 12")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.text = element_text(color = "black", size = rel(1.5)),
        legend.position=c(0.18,0.2))+labs(fill="",col="")
p.norm_bi
```


```{r p.norm_L}
normwave_amy_L <- normwave_amy_L %>% mutate(subdivision = "Whole")
normwave_amy_me_L <- normwave_amy_me_L %>% mutate(subdivision = "Medial")
# normwave_amy_la_L <- normwave_amy_la_L %>% mutate(subdivision = "Lateral")
normwave_L <- rbind(normwave_amy_L, normwave_amy_me_L)
normwave_L$subdivision <- 
  factor(normwave_L$subdivision, levels=c("Medial","Whole"))

p.norm_L <- normwave_amy_L %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  # geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .2)+
  geom_line(aes(col = subdivision),size=1.2)+
  annotate("rect", xmin=-8, xmax=10, ymin=-1.5, ymax=3, fill="gray")+
  scale_color_manual(values=c("green4"))+
  scale_fill_manual(values=c("green4"))+
  scale_y_continuous(limits=c(-13,15.4), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-120,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Left (2), medial = 2, lateral = 0")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_L
```

```{r p.norm_R}
normwave_amy_R <- normwave_amy_R %>% mutate(subdivision = "Whole")
normwave_amy_me_R <- normwave_amy_me_R %>% mutate(subdivision = "Medial")
normwave_amy_la_R <- normwave_amy_la_R %>% mutate(subdivision = "Lateral")
normwave_R <- rbind(normwave_amy_R, normwave_amy_me_R,normwave_amy_la_R)
normwave_R$subdivision <- 
  factor(normwave_R$subdivision, levels=c("Lateral","Medial","Whole"))

p.norm_R <- normwave_R %>% ggplot(aes(Time, norm))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  geom_ribbon(aes(ymin=norm-se, ymax=norm+se, fill = subdivision), alpha = .22)+
  geom_line(aes(col = subdivision),size=1.2)+
  # whole
  annotate("rect", xmin=54, xmax=64, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  annotate("rect", xmin=170, xmax=210, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  annotate("rect", xmin=403, xmax=438, ymin=14.8, ymax=15.4, fill="dodgerblue3")+
  # medial
  # lateral
  annotate("rect", xmin=173, xmax=190, ymin=13.2, ymax=13.8, fill="maroon3")+
  annotate("rect", xmin=378, xmax=400, ymin=13.2, ymax=13.8, fill="maroon3")+
  
  annotate("rect", xmin=-8, xmax=10, ymin=-3, ymax=2.5, fill="gray")+
  scale_color_manual(values=c("maroon3","green4","dodgerblue3"))+
  scale_fill_manual(values=c("maroon3","green4","dodgerblue3"))+
  scale_y_continuous(limits=c(-13,15.4), breaks = c(-10,-5,0,5,10,15))+
  scale_x_continuous(limits=c(-120,500), breaks = c(-100,0,100,200,300,400,500))+
  xlab("Time (ms)")+ylab("Amplitude (SD)")+ 
  ggtitle("Right (24), medial = 12, lateral = 12")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.5)))+
  theme(axis.title = element_text(color = "black", size = 18))+
  theme(plot.title = element_text(color = "black", size = 18))+
  theme(legend.position="none")+labs(fill="",col="")
p.norm_R
```


```{r}
filename <- "CCEP_R-IFG_AMY_mela_35Hz.pdf"
pdf(file = filename, height = 4.5, width = 5)
p.norm_bi
p.norm_L
p.norm_R
dev.off()
```

