---
title: "iTEP all statistics"
output: html_document
date: "2023-08-28"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(lme4)
library(lmerTest)
library(readr)
library(patchwork)
library(ggsignif)
library(psych) # load correlation
library(RColorBrewer)#color
library(car)
# load("C:/Users/xjl19/Desktop/TMS-iEEG/Stanford_Processed/TEP/iTEP_all.RData")
rootpath <- "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/"
wd <- paste0(rootpath,"allPatients_iEEGdata_csv/iTEP_csv_L-DLPFC_amy/1hp_detrend500")
wd <- paste0(rootpath,"allPatients_iEEGdata_csv/iTEP_csv_L-DLPFC_amy/2hp_detrend500")
wd <- paste0(rootpath,"allPatients_iEEGdata_csv/iTEP_csv_L-DLPFC_amy/2hp_detrend500_cutaneous")
wd <- paste0(rootpath,"allPatients_iEEGdata_csv/iTEP_csv_R-Parietal_amy/2hp_detrend500")
wd <- paste0(rootpath,"allPatients_iEEGdata_csv/iTEP_csv_R-DLPFC_amy/2hp_detrend500")
setwd(wd)

```

### Read neural data

```{r read new TEP csv}
TEP_amy <- read_csv(list.files(wd, pattern = '*.csv'))
names(TEP_amy) <- c("Patient","Condition","TrialNumber","Channel","Time","Amplitude")
TEP_amy$Time <- TEP_amy$Time*1000
TEP_amy$Channel <- paste(TEP_amy$Patient, TEP_amy$Channel, sep = "_")
TEP_amy$Condition <- factor(TEP_amy$Condition, levels = c("tms", "sham"))

TEP_amy_cu <- read_csv(list.files(wd, pattern = '*.csv'))
TEP_amy_cu$Time <- TEP_amy_cu$Time*1000
TEP_amy_cu$Channel <- paste(TEP_amy_cu$Patient, TEP_amy_cu$Channel, sep = "_")
TEP_amy_cu <- TEP_amy_cu %>% mutate(Condition = "sham2")
# delete questionable channels l dlpfc
TEP_amy <- filter(TEP_amy, Patient != 672 & 
                    Channel != "593_LFPx183" &
                    Channel != "593_LFPx184" &
                    Channel != "593_LFPx185" &
                    Channel != "593_LFPx231" &
                    Channel != "430_LFPx14" 
                    )
TEP_amy_cu <- filter(TEP_amy_cu, 
                    Channel != "593_LFPx183" &
                    Channel != "593_LFPx184" &
                    Channel != "593_LFPx185" &
                    Channel != "593_LFPx231")

# delete questionable channels r parietal
TEP_amy <- filter(TEP_amy, 
                    Channel != "405_LFPx77" &
                    Channel != "405_LFPx78" &
                    Channel != "423_LFPx79" &
                    Channel != "423_LFPx80" &
                    Channel != "423_LFPx82" )

ChannelList <- TEP_amy %>% group_by(Channel) %>% 
  summarise(Patient = mean(Patient))
ChannelList <- ChannelList[[1]]
ChannelList_cu <- TEP_amy_cu %>% group_by(Channel) %>%
  summarise(Patient = mean(Patient))
ChannelList_cu <- ChannelList_cu[[1]]

# add ROI info
chlinfo_amy <- read_excel(paste0(rootpath, "Selected_Channel_AMY.xlsx"),
                          sheet = "TMS L-DLPFC")
chlinfo_amy <- read_excel(paste0(rootpath, "Selected_Channel_AMY.xlsx"),
                          sheet = "TMS R-Parietal")
chlinfo_amy <- read_excel(paste0(rootpath, "Selected_Channel_AMY.xlsx"),
                          sheet = "TMS R-DLPFC")

chlinfo_amy$Channel <- paste(chlinfo_amy$Patient, chlinfo_amy$Channel, sep = "_LFPx")
TEP_amy <- left_join(TEP_amy, chlinfo_amy[c(2,15,23)])
TEP_amy_cu <- left_join(TEP_amy_cu, chlinfo_amy[c(2,15,23)])
```

### Plot TEP

```{r plot Amd iTEP, echo=FALSE}
TEP_amy <- TEP_amy %>% mutate(Cutaneous = "No")
TEP_amy_cu <- TEP_amy_cu %>% mutate(Cutaneous = "Yes")
TEP_amy_all <- rbind(TEP_amy, filter(TEP_amy_cu, Condition == "sham2"))
TEP_amy_all <- TEP_amy_all %>% filter(Patient > 592)
TEP_amy_all$Cutaneous <- factor(TEP_amy_all$Cutaneous)
TEP_amy_all$Channel <- factor(TEP_amy_all$Channel, levels = c("593_LFPx186","593_LFPx187","634_LFPx57","593_LFPx233","593_LFPx234"))

# TEP_amy_all
baseline_amy_all <- filter(TEP_amy_all, Time <= -50 & Time >=-250) %>%
  group_by(Patient,Condition,Channel,Cutaneous,DKT,is_lateral) %>% 
  summarise(base_mean = mean(Amplitude), base_sd = sd(Amplitude))
TEP_amy_all <- TEP_amy_all %>% left_join(baseline_amy_all) %>% 
  mutate(iTEP_norm = (Amplitude - base_mean)/base_sd,
         SDchange = abs((Amplitude - base_mean)/base_sd))
summary(TEP_amy_all)
# TEP_amy %>% # 672 amygdala
# filter(TEP_amy_cu, Time <= 450 & Time >= -250) %>% 
# filter(TEP_amy_sham, Patient > 592 & Time <= 450 & Time >= -250) %>% 


TEP_amy_all %>%
  filter(Time <= 450 & Time >= -250) %>% 
  group_by(Channel, Condition, Time, Cutaneous) %>%
  summarise(mean_amplitude = mean(iTEP_norm), se = sd(iTEP_norm)/sqrt(40)) %>%
  ggplot(aes(Time, mean_amplitude))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  geom_ribbon(aes(ymin=mean_amplitude-se, ymax=mean_amplitude+se, fill = Condition), alpha = .2)+
  stat_summary(aes(col=Condition,linetype=Cutaneous), geom="line", size=1, alpha = .9)+
  annotate("rect", xmin=-10, xmax=25, ymin=-1, ymax=1, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","darkgray","gray40"),
                     labels=c("TMS","Sham","Sham w/ cutaneous"))+
  scale_fill_manual(values=c("dodgerblue3","darkgray","gray40"),
                    labels=c("TMS","Sham","Sham w/ cutaneous"))+
  ylim(-2.5,2)+
  ylab("Amplitude (SD)")+xlab("Time (ms)")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=1))+
  theme(axis.ticks=element_line(color="black",size=1,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.3)))+
  theme(axis.title = element_text(color = "black", size = 16))+
  theme(legend.text = element_text(color = "black", size = 16))+
  theme(legend.position=c(0.85,0.22))+labs(fill="",col="",linetype="")+
  facet_wrap(~Channel)


```


```{r removing trials}
TEP_amy <- filter(TEP_amy, Time >= -250 & Time <= 500)

# calculate baseline SD for each trial
base_trl_amy <- filter(TEP_amy, Time < -50) %>%
  group_by(Channel, TrialNumber) %>% 
  summarise(base_trl_mean = mean(Amplitude), 
            base_trl_sd = sd(Amplitude))
TEP_amy <- TEP_amy %>% left_join(base_trl_amy) %>% 
  mutate(SDchange = abs((Amplitude - base_trl_mean)/base_trl_sd),
         SD = abs(Amplitude)/base_trl_sd)

# identify trials to be removed
TEP_amy_25ms <- filter(TEP_amy, Time == 25 & SD > 10)
TEP_amy_25_450ms <- filter(TEP_amy, Time > 25 & SD > 50)
Deleted <- rbind(TEP_amy_25ms, TEP_amy_25_450ms) %>% 
  mutate(delete = 1) %>% 
  group_by(Channel, TrialNumber) %>% 
  summarise(delete = mean(delete))
TEP_amy <- TEP_amy %>% left_join(Deleted)

# removing trials
TEP_amy <- TEP_amy %>% filter(is.na(delete))
```


```{r filtering bad trials}
# TEP_amy <- left_join(TEP_amy, chlinfo_amy[c(2,4,5)])
TEP_amy_TMS <- filter(TEP_amy, Condition == "tms")
TEP_amy_Sham <- filter(TEP_amy, Condition == "sham")

BadTrials_TMS <- TEP_amy_TMS %>% group_by(Channel, TrialNumber) %>%
  summarise(TrialNumber = mean(TrialNumber)) %>% 
  left_join(chlinfo_amy[c(2,4)]) %>% 
  mutate(bad = 0)
BadTrials_Sham <- TEP_amy_Sham %>% group_by(Channel, TrialNumber) %>%
  summarise(TrialNumber = mean(TrialNumber)) %>% 
  left_join(chlinfo_amy[c(2,5)]) %>% 
  mutate(bad = 0)

for (i in 1:nrow(BadTrials_TMS)){
  if (BadTrials_TMS$TrialNumber[i] %in%
      as.numeric(strsplit(BadTrials_TMS$BadTrials_TMS[i], ";")[[1]])){
      BadTrials_TMS$bad[i] <- 1
      }
}
TEP_amy_TMS <- left_join(TEP_amy_TMS, BadTrials_TMS)
TEP_amy_TMS <- filter(TEP_amy_TMS, bad == 0)

for (i in 1:nrow(BadTrials_Sham)){
  if (BadTrials_Sham$TrialNumber[i] %in%
      as.numeric(strsplit(BadTrials_Sham$BadTrials_Sham[i], ";")[[1]])){
      BadTrials_Sham$bad[i] <- 1
      }
}
TEP_amy_Sham <- left_join(TEP_amy_Sham, BadTrials_Sham)
TEP_amy_Sham <- filter(TEP_amy_Sham, bad == 0)

TEP_amy <- rbind(TEP_amy_TMS[-14], TEP_amy_Sham[-14])
rm(TEP_amy_Sham)
rm(TEP_amy_TMS)

TEP_amy_cu <- TEP_amy_cu[,c(1:8)] %>%
  rbind(filter(TEP_amy[,c(1:8)], Patient == "593" | Patient == "634"))

TEP_amy_cu$Condition <- factor(TEP_amy_cu$Condition, levels = c("tms","sham","sham2"))

p <- TEP_amy[,c(1:8)] %>%
  filter(Time <= 500 & Time >= -250) %>% 
  group_by(Channel, Condition, Time) %>%
  summarise(mean_amplitude = mean(Amplitude), se = sd(Amplitude)/sqrt(40)) %>%
  ggplot(aes(Time, mean_amplitude))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  geom_ribbon(aes(ymin=mean_amplitude-se, ymax=mean_amplitude+se, fill = Condition), alpha = .2)+
  stat_summary(aes(col=Condition), geom="line", size=.8, alpha = .9)+
  annotate("rect", xmin=-14, xmax=28, ymin=-10, ymax=10, fill="white")+
  annotate("rect", xmin=-14, xmax=28, ymin=-10, ymax=10, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","darkgray"),
                     labels=c("TMS","Sham"))+
  scale_fill_manual(values=c("dodgerblue3","darkgray"),
                    labels=c("TMS","Sham"))+
  ylim(-10,10)+
  ylab("Amplitude (SD)")+xlab("Time (ms)")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.3)))+
  theme(axis.title = element_text(color = "black", size = 16))+
  theme(legend.text = element_text(color = "black", size = 15))+
  labs(fill="",col="",linetype="")+
  facet_wrap(~Channel)
p

p.cu <- TEP_amy[,c(1:8)] %>%
  filter(Patient == 593) %>% 
  filter(Time <= 500 & Time >= -250) %>% 
  group_by(Channel, Condition, Time) %>%
  summarise(mean_amplitude = mean(Amplitude), se = sd(Amplitude)/sqrt(40)) %>%
  ggplot(aes(Time, mean_amplitude))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  geom_ribbon(aes(ymin=mean_amplitude-se, ymax=mean_amplitude+se, fill = Condition), alpha = .2)+
  stat_summary(aes(col=Condition), geom="line", size=.8, alpha = .9)+
  annotate("rect", xmin=-14, xmax=28, ymin=-20, ymax=15, fill="white")+
  annotate("rect", xmin=-14, xmax=28, ymin=-8, ymax=5, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","darkgray","gray40"),
                     labels=c("TMS","Sham","Sham w/ cutaneous"))+
  scale_fill_manual(values=c("dodgerblue3","darkgray","gray40"),
                    labels=c("TMS","Sham","Sham w/ cutaneous"))+
  ylim(-20,15)+
  ylab("Amplitude (SD)")+xlab("Time (ms)")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.3)))+
  theme(axis.title = element_text(color = "black", size = 16))+
  theme(legend.text = element_text(color = "black", size = 15))+
  labs(fill="",col="",linetype="")+
  facet_wrap(~Channel)
p.cu


```

```{r save cutaneous sham results}
figDir = "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/1_Figures"
setwd(figDir)
filename <- "iTEP_L-DLPFC_AMY_2hp_detrend500_cu.pdf"
pdf(file = filename, height = 5, width = 7.5)
p.cu
dev.off()
```


```{r filtering bad cutaneous trials}
BadTrials_cu_Sham <- TEP_amy_cu %>% group_by(Channel, TrialNumber) %>%
  summarise(TrialNumber = mean(TrialNumber)) %>% 
  left_join(chlinfo_amy[c(2,3)]) %>% 
  mutate(bad = 0)

for (i in 1:nrow(BadTrials_cu_Sham)){
  if (BadTrials_cu_Sham$TrialNumber[i] %in%
      as.numeric(strsplit(BadTrials_cu_Sham$BadTrials_Sham2[i], ";")[[1]])){
      BadTrials_cu_Sham$bad[i] <- 1
      }
}
TEP_amy_cu <- left_join(TEP_amy_cu, BadTrials_cu_Sham)
TEP_amy_cu <- filter(TEP_amy_cu, bad == 0)
```


```{r}
setwd('/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/Documents - JingJiang Lab/JiangLab/4_Projects/2_DLPFC_AMY_Bella/2_TMS_iEEG')
write.csv(filter(TEP_amy[c(1:8)], Condition == 'tms'), "TEP_amy_tms_LDLPFC.csv")
write.csv(filter(TEP_amy[c(1:8)], Condition == 'tms'), "TEP_amy_tms_RParietal.csv")
```


## normalization

```{r amygdala iTEP normalization}
TEP_amy_avg  <- TEP_amy %>% 
  group_by(Patient, Condition, Channel, Time, DKT, is_lateral) %>% 
  summarise(iTEP = mean(Amplitude))
summary(TEP_amy_avg)

# calculate baseline for normalization
baseline_amy <- filter(TEP_amy_avg, Time <= -50 & Time >=-250) %>%
  group_by(Patient, Condition, Channel) %>% summarise(base_mean = mean(iTEP), 
                                           base_sd = sd(iTEP))
TEP_amy_avg <- TEP_amy_avg %>% left_join(baseline_amy) %>% 
  mutate(iTEP_norm = (iTEP - base_mean)/base_sd,
         SDchange = abs((iTEP - base_mean)/base_sd))


# write.csv(TEP_amy_avg, "TEP_amy_avg.csv")

# average across trials for cutaneous sham
TEP_amy_cu_avg  <- TEP_amy_cu %>% 
  group_by(Patient, Condition, Channel, Time, DKT, is_lateral) %>% 
  summarise(iTEP = mean(Amplitude))
summary(TEP_amy_cu_avg)

# calculate baseline for normalization
baseline_amy_sham2 <- filter(TEP_amy_cu_avg, Time < -50 & Time >=-250) %>%
  group_by(Patient, Condition, Channel) %>% summarise(base_mean = mean(iTEP), 
                                           base_sd = sd(iTEP))
TEP_amy_cu_avg <- TEP_amy_cu_avg %>% left_join(baseline_amy_sham2) %>% 
  mutate(iTEP_norm = (iTEP - base_mean)/base_sd,
         SDchange = abs((iTEP - base_mean)/base_sd))

# Combining tms, sham, sham2
TEP_amy_cutaneous_avg <- TEP_amy_avg %>% 
  filter(Patient == 593 | Patient == 634) %>% 
  rbind(TEP_amy_cu_avg)
TEP_amy_cutaneous_avg$Condition <- 
  factor(TEP_amy_cutaneous_avg$Condition, levels = c("tms", "sham", "sham2"))

p.sd <- TEP_amy_avg %>%
  filter(Time <= 500 & Time >= -250) %>% 
  ggplot(aes(Time, iTEP_norm))+
  geom_hline(yintercept=0, linetype="dotted", size = .8, col = "darkgray")+
  stat_summary(aes(col=Condition), geom="line", size=1.5, alpha = .9)+
  annotate("rect", xmin=-14, xmax=28, ymin=-20, ymax=20, fill="white")+
  annotate("rect", xmin=-14, xmax=28, ymin=-20, ymax=20, fill="gray")+
  scale_color_manual(values=c("dodgerblue3","darkgray"),
                     labels=c("TMS","Sham"))+
  scale_fill_manual(values=c("dodgerblue3","darkgray"),
                    labels=c("TMS","Sham"))+
  ylim(-20,20)+
  ylab("Amplitude (SD)")+xlab("Time (ms)")+theme_classic()+
  theme(axis.line=element_line(linetype=1,color="black",size=.8))+
  theme(axis.ticks=element_line(color="black",size=.8,lineend = 12))+
  theme(axis.text = element_text(color = "black", size = rel(1.3)))+
  theme(axis.title = element_text(color = "black", size = 16))+
  theme(legend.text = element_text(color = "black", size = 15))+
  labs(fill="",col="",linetype="")+
  facet_wrap(~Channel)
p.sd

```


## Load and rearrange tvs data

```{r}
# load("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/iTEP_csv_L-DLPFC_amy/iTEPamy_removed_cleaned.RData")
# write.csv(TEP_amy_avg_tvs, "/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/iTEP_csv_L-DLPFC_amy/TEP_amy_avg_tvs.csv")
# 
# TEP_amy_avg_tvs <- read.csv("/Users/xianqliu/Library/CloudStorage/OneDrive-UniversityofIowa/1_TMS_iEEG/3_ProcessedData_Backup/iTEP_csv_L-DLPFC_amy/TEP_amy_avg_tvs.csv")[-1]
# 
# TEP_amy_avg_tvs <- TEP_amy_avg_tvs[c(1:6,10)] %>% 
#   pivot_wider(names_from = Condition, values_from = iTEP_norm)
# 
# timecourse <- c(26:450)
```

## Comparing normalized amplitude: tms vs sham

```{r Both amyg}
# paired t-test
timecourse <- c(26:500) # timewin: 25ms ~ 450 ms
TEP_amy_avg_tvs <- TEP_amy_avg[c(1:6,10)] %>% pivot_wider(names_from = Condition, values_from = iTEP_norm)
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i])
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    data.frame(t.tvs$statistic) %>% 
    mutate(p.value = t.tvs$p.value) %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(p.value>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_B <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% filter(Condition == "tms")
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))


# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))

coef_tvs_B <- coef_tvs_B %>% left_join(stats_amy_sig[c(3,6)])

```



```{r Both amyg medial}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            is_lateral == 0)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    data.frame(t.tvs$statistic) %>% 
    mutate(p.value = t.tvs$p.value) %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(p.value>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_B_me <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% filter(Condition == "tms" & is_lateral == 0)
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))


# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig_me <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))

coef_tvs_B_me <- coef_tvs_B_me %>% left_join(stats_amy_sig_me[c(3,6)])
```



```{r Both amyg lateral}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            is_lateral == 1)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    t.tvs$p.value %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(.>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$.
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_B_la <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% filter(Condition == "tms" & is_lateral == 1)
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))


# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig_la <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))
```


```{r Left amyg}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] & 
                            DKT == "Left-Amygdala")
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    t.tvs$p.value %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(.>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$.
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_L <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r Left amyg medial}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            DKT == "Left-Amygdala" &
                            is_lateral == 0)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    t.tvs$p.value %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(.>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$.
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_L_me <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r Left amyg lateral}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            DKT == "Left-Amygdala" &
                            is_lateral == 1)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    t.tvs$p.value %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(.>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$.
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_L_la <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```




```{r Right amyg}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            DKT == "Right-Amygdala")
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    data.frame(t.tvs$statistic) %>% 
    mutate(p.value = t.tvs$p.value) %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(p.value>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_R <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% 
  filter(Condition == "tms" & DKT == "Right-Amygdala")
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))

# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig_R <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))

coef_tvs_R <- coef_tvs_R %>% left_join(stats_amy_sig_R[c(3,6)])
```


```{r Right amyg medial}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            DKT == "Right-Amygdala" &
                            is_lateral == 0)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    data.frame(t.tvs$statistic) %>% 
    mutate(p.value = t.tvs$p.value) %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(p.value>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_R_me <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% 
  filter(Condition == "tms" & DKT == "Right-Amygdala" & is_lateral == 0)
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))

# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig_R_me <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))

coef_tvs_R_me <- coef_tvs_R_me %>% left_join(stats_amy_sig_R_me[c(3,6)])
```

```{r Right amyg lateral}
# paired t-test
coef_tvs <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tvs, Time == timecourse[i] &
                            DKT == "Right-Amygdala" &
                            is_lateral == 1)
  t.tvs <- t.test(TEP_timepoint$tms, TEP_timepoint$sham, paired = T)
  
  coef_new <- 
    t.tvs$p.value %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef_tvs <- bind_rows(coef_tvs,coef_new)
}
coef_tvs <- coef_tvs %>% 
  mutate(sig_tvs = ifelse(.>0.05, 0, 1))

# multiple comparison correction
plist <- coef_tvs$.
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef_tvs_R_la <- coef_tvs %>% mutate(corrected_p = plist_adj) %>% 
  mutate(corrected_sig = ifelse(corrected_p < 0.05, 1, 0))
```

```{r}
TEP_amy_avg_tms <- TEP_amy_avg %>% 
  filter(Condition == "tms" & DKT == "Right-Amygdala" & is_lateral == 1)
baseline_mean <- TEP_amy_avg_tms %>% 
  filter(Time < -50) %>% group_by(Channel) %>% 
  summarise(baseline_mean = mean(iTEP_norm))

# amplitude
coef <- data.frame()
for (i in 1:length(timecourse)){
  TEP_timepoint <- filter(TEP_amy_avg_tms, Time == timecourse[i])
  TEP_timepoint <- left_join(TEP_timepoint, baseline_mean)
  if (mean(TEP_timepoint$iTEP_norm) >= 0) {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "greater")
  } else {
    tt <- t.test(TEP_timepoint$iTEP_norm, TEP_timepoint$baseline_mean, paired = T, alternative = "less")
  }

  coef_new <- 
    tt[c(1,3)] %>% 
    data.frame() %>% 
    mutate(time = timecourse[i])
  coef <- bind_rows(coef,coef_new)
}
coef <- coef %>% mutate(sig = ifelse(p.value>0.05, 0, 1))

plist <- coef$p.value
plist_adj <- p.adjust(plist,  method ="BH") # FDR
coef <- coef %>% mutate(corrected_sig = plist_adj)

stats_amy_sig_R_la <- coef %>% 
  mutate(is_sig = ifelse(corrected_sig < 0.05, 1, 0))
```

## Comparing ptp range

```{r ptp1 100}
# whole
ptp1_amy <- 
  filter(TEP_amy_avg, Time >= 26 & Time <= 100) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy, alternative ="greater") # t = 4.4099, df = 29, p-value = 0.0000651
# medial
ptp1_amy_me <- 
  filter(TEP_amy_avg,  Time >= 26 & Time <= 100 & is_lateral == 0) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_me, alternative ="greater") # t = 3.4951, df = 17, p-value = 0.001387
# lateral
ptp1_amy_la <-
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & is_lateral == 1) %>% 
  group_by(Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_la, alternative ="greater") #t = 2.6601, df = 11, p-value = 0.01109

p.adjust(c(0.0000651,0.001387,0.01109), method="bonferroni") # 0.0001953 0.0041610 0.0332700

# left
ptp1_amy_L <- 
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
# ptp1_amy_L <- filter(ptp1_amy_L, Patient != "634")
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_L, alternative ="greater") 
# medial
ptp1_amy_L_me <- 
  filter(TEP_amy_avg,  Time >= 26 & Time <= 100 & is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_L_me, alternative ="greater") 
# lateral
ptp1_amy_L_la <-
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_L_la, alternative ="greater") 



# right
ptp1_amy_R <- 
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
# ptp1_amy_R <- filter(ptp1_amy_R, Patient != "634")
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_R, alternative ="greater") #t = 4.4999, df = 21, p-value = 0.00009834
# medial
ptp1_amy_R_me <- 
  filter(TEP_amy_avg,  Time >= 26 & Time <= 100 & is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_R_me, alternative ="greater") # t = 3.5398, df = 14, p-value = 0.001633
# lateral
ptp1_amy_R_la <-
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & is_lateral == 1 & DKT == "Right-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
t.test(range1 ~ Condition, paired = T, data = ptp1_amy_R_la, alternative ="greater") #t = 3.8583, df = 6, p-value = 0.004189

p.adjust(c(0.00009834,0.001633,0.004189), method="bonferroni") # 0.00029502 0.00489900 0.01256700

ptp1_amy_mela <- 
  filter(TEP_amy_avg, Time >= 26 & Time <= 100 & Condition == "tms") %>% 
  group_by(is_lateral, Channel) %>% 
  summarise(range1 = max(iTEP_norm)-min(iTEP_norm))
# ptp1_amy_mela <- filter(ptp1_amy_mela, Channel != "429_LFPx123" & Channel != "634_LFPx55" & Channel != "634_LFPx56")
t.test(range1 ~ is_lateral, data = ptp1_amy_mela, alternative ="greater")

```



```{r ptp2 150}
# whole
ptp2_amy <- 
  filter(TEP_amy_avg, Time >= 50 & Time <= 250) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
# ptp2_amy <- filter(ptp2_amy, Patient != "634")
t.test(range2 ~ Condition, paired = T, data = ptp2_amy, alternative ="greater") # t = 2.4608, df = 29, p-value = 0.01003
# medial
ptp2_amy_me <- 
  filter(TEP_amy_avg,  Time >= 50 & Time <= 250 & is_lateral == 0) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_me, alternative ="greater") # t = 2.3321, df = 17, p-value = 0.01612
# lateral
ptp2_amy_la <-
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & is_lateral == 1) %>% 
  group_by(Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_la, alternative ="greater") #t = 0.8993, df = 11, p-value = 0.1939

p.adjust(c(0.01003,0.01612,0.1939), method="bonferroni") # 0.03009 0.04836 0.58170

# left
ptp2_amy_L <- 
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
# ptp2_amy_L <- filter(ptp2_amy_L, Patient != "634")
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_L, alternative ="greater") #t = 0.90235, df = 7, p-value = 0.1984
# medial
ptp2_amy_L_me <- 
  filter(TEP_amy_avg,  Time >= 50 & Time <= 250 & is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_L_me, alternative ="greater") # t = -2.2623, df = 2, p-value = 0.924
# lateral
ptp2_amy_L_la <-
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_L_la, alternative ="greater") #t = 1.1738, df = 4, p-value = 0.1528



# right
ptp2_amy_R <- 
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
# ptp2_amy_R <- filter(ptp2_amy_R, Patient != "634")
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_R, alternative ="greater") #t = 2.2833, df = 21, p-value = 0.01647
# medial
ptp2_amy_R_me <- 
  filter(TEP_amy_avg,  Time >= 50 & Time <= 250 & is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_R_me, alternative ="greater") # t = 2.5273, df = 14, p-value = 0.01208
# lateral
ptp2_amy_R_la <-
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & is_lateral == 1 & DKT == "Right-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
t.test(range2 ~ Condition, paired = T, data = ptp2_amy_R_la, alternative ="greater") #t = 0.019838, df = 6, p-value = 0.4924

p.adjust(c(0.01647,0.01208,0.4924), method="bonferroni") # 0.04941 0.03624 1.00000

ptp2_amy_mela <- 
  filter(TEP_amy_avg, Time >= 50 & Time <= 250 & Condition == "tms") %>% 
  group_by(is_lateral, Channel) %>% 
  summarise(range2 = max(iTEP_norm)-min(iTEP_norm))
# ptp2_amy_mela <- filter(ptp2_amy_mela, Channel != "429_LFPx123" & Channel != "634_LFPx55" & Channel != "634_LFPx56")
t.test(range2 ~ is_lateral, data = ptp2_amy_mela, alternative ="greater")

p.adjust(c(0.010,0.016,0.194), method="bonferroni")
```



```{r ptp3 400}
# whole
ptp3_amy <- 
  filter(TEP_amy_avg, Time >=150 & Time <= 400) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
# ptp3_amy <- filter(ptp3_amy, Patient != "634")
t.test(range3 ~ Condition, paired = T, data = ptp3_amy, alternative ="greater") # t = 2.0693, df = 29, p-value = 0.02377
# medial
ptp3_amy_me <- 
  filter(TEP_amy_avg,  Time >=150 & Time <= 400 & is_lateral == 0) %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_me, alternative ="greater") # t = 1.6321, df = 17, p-value = 0.06052
# lateral
ptp3_amy_la <-
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & is_lateral == 1) %>% 
  group_by(Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_la, alternative ="greater") #t = 1.3107, df = 11, p-value = 0.1083

p.adjust(c(0.01003,0.01612,0.1939), method="bonferroni") # 0.03009 0.04836 0.58170

# left
ptp3_amy_L <- 
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
# ptp3_amy_L <- filter(ptp3_amy_L, Patient != "634")
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_L, alternative ="greater") #t = 0.90235, df = 7, p-value = 0.1984
# medial
ptp3_amy_L_me <- 
  filter(TEP_amy_avg,  Time >=150 & Time <= 400 & is_lateral == 0 & DKT == "Left-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_L_me, alternative ="greater") # t = -2.2623, df = 2, p-value = 0.924
# lateral
ptp3_amy_L_la <-
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & is_lateral == 1 & DKT == "Left-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_L_la, alternative ="greater") #t = 1.1738, df = 4, p-value = 0.1528



# right
ptp3_amy_R <- 
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
# ptp3_amy_R <- filter(ptp3_amy_R, Patient != "634")
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_R, alternative ="greater") #t = 2.2833, df = 21, p-value = 0.01647
# medial
ptp3_amy_R_me <- 
  filter(TEP_amy_avg,  Time >=150 & Time <= 400 & is_lateral == 0 & DKT == "Right-Amygdala") %>% 
  group_by(Patient, Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_R_me, alternative ="greater") # t = 2.5273, df = 14, p-value = 0.01208
# lateral
ptp3_amy_R_la <-
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & is_lateral == 1 & DKT == "Right-Amygdala") %>% 
  group_by(Condition, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
t.test(range3 ~ Condition, paired = T, data = ptp3_amy_R_la, alternative ="greater") #t = 0.019838, df = 6, p-value = 0.4924

p.adjust(c(0.01647,0.01208,0.4924), method="bonferroni") # 0.04941 0.03624 1.00000

ptp3_amy_mela <- 
  filter(TEP_amy_avg, Time >=150 & Time <= 400 & Condition == "tms") %>% 
  group_by(is_lateral, Channel) %>% 
  summarise(range3 = max(iTEP_norm)-min(iTEP_norm))
# ptp3_amy_mela <- filter(ptp3_amy_mela, Channel != "429_LFPx123" & Channel != "634_LFPx55" & Channel != "634_LFPx56")
t.test(range3 ~ is_lateral, data = ptp3_amy_mela, alternative ="greater")

p.adjust(c(0.010,0.016,0.194), method="bonferroni")
```